namespace Corregedoria.Domain.Enum
{
    public enum ETipoOrgao
    {
        SELECIONE = 0,
        GOVERNADORIA = 1,
        CASA_CIVIL = 2,
        PGE = 3,
        SECOM = 4,
        SEPL = 5,
        SEIMT = 6,
        SEAP = 7,
        SEAB = 8,
        SECID = 9,
        SEIL = 10,
        SEED = 11,
        SESP = 12,
        SESA = 13,
        SEFA = 14,
        SEDEST = 15,
        SEIC = 16,
        SEJU = 17,
        SETI = 18,
        SEMI = 19,
        SEDEF = 20,
        SEEC = 21,
        SETR = 22,
        SETU = 23,
        RECEITA = 24,
        CEP = 25,
        ADAPAR = 26,
        AGEPAR = 27,
        AMEP = 28,
        CCTG = 29,
        DER = 30,
        DETRAN = 31,
        IAT = 32,
        IAPAR_EMATER = 33,
        IPEM = 34,
        PARANAESPORTE = 35,
        IPARDES = 36,
        FUNDEPAR = 37,
        JUCEPAR = 38,
        LOTEPAR = 39,
        UEL = 40,
        UEM = 41,
        UEPG = 42,
        UNICENTRO = 43,
        UENP = 44,
        UNIOESTE = 45,
        UNESPAR = 46,
        FA = 47,
        FUNEAS = 48,
        FAASP = 49,
        APPA = 50,
        TECPAR = 51,
        CEASA = 52,
        COHAPAR = 53,
        SANEPAR = 54,
        CELEPAR = 55,
        COPEL = 56,
        FERROESTE = 57,
        FOMENTOPARANA = 58,
        CGE = 59,
        CM = 60,
        CEDEC = 61,
        SGRI = 62,
        SGAS = 63,
        SAR = 64,
        SUDIS = 65,
        SGDES = 66,
        SDBH = 67,
        DEPPEN = 68,


    }
}
